name: Linux Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  INSTALL_PATH: /home/runner/Mp4Decrypt
  
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    
    - name: Prepare library
      run: |
        mkdir ${{ env.INSTALL_PATH }}
        mkdir temp
        git clone https://github.com/axiomatic-systems/Bento4
        cp -r src/. temp
        cp -r Bento4/Source/C++/Core/. src
        cp -r Bento4/Source/C++/Codecs/. src
        cp -r Bento4/Source/C++/Crypto/. src
        cp -r Bento4/Source/C++/MetaData/. src
        cp -r temp/. src

    - name: Build library
      run: |
        cmake -B build -D CMAKE_INSTALL_PREFIX=${{ env.INSTALL_PATH }} -D CMAKE_BUILD_TYPE=Release
        cmake --build build --config Release
        sudo cmake --install build
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Linux-artifact
        path: ${{ env.INSTALL_PATH }}
        if-no-files-found: ignore
        retention-days: 0
