name: Windows Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v4
    - name: Prepare library
      shell: cmd
      run: |
        mkdir temp
        mkdir upload\lib
        mkdir upload\include\Mp4Decrypt
        git clone https://github.com/axiomatic-systems/Bento4
        copy src\*.cpp temp
        copy /y /v "Bento4\Source\C++\Core\*.h" src
        copy /y /v "Bento4\Source\C++\Core\*.cpp" src
        copy /y /v "Bento4\Source\C++\Codecs\*.h" src
        copy /y /v "Bento4\Source\C++\Codecs\*.cpp" src
        copy /y /v "Bento4\Source\C++\Crypto\*.h" src
        copy /y /v "Bento4\Source\C++\Crypto\*.cpp" src
        copy /y /v "Bento4\Source\C++\MetaData\*.h" src
        copy /y /v "Bento4\Source\C++\MetaData\*.cpp" src
        copy /y /v temp\*.cpp src
        
    - name: Build library
      shell: cmd
      run: |
        cmake -B build -D CMAKE_BUILD_TYPE=Release
        cmake --build build --config Release
        copy /y /v include upload\include\Mp4Decrypt
        copy /y /v build\Release\*.lib upload\lib
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Windows-artifact
        path: ${{github.workspace}}/upload
        if-no-files-found: ignore
        retention-days: 0
